package integra.jna;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.PointerByReference;

import java.nio.IntBuffer;
/**
 * JNA Wrapper for library <b>iGammaJNA</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IGammaJNALibrary implements Library {
	public static final String JNA_LIBRARY_NAME = "iGammaJNA";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(IGammaJNALibrary.JNA_LIBRARY_NAME);
	static {
		Native.register(IGammaJNALibrary.JNA_LIBRARY_NAME);
	}
	/**
	 * Original signature : <code>void iGammaJnaFree(void*)</code><br>
	 * <i>native declaration : iGammaJNAiGammaJNA.h:52</i>
	 */
	public static native void iGammaJnaFree(Pointer p);
	/**
	 * Original signature : <code>int iGammaJnaConnect(const char*, const char*, const char*, const char*, const char*, void**, char**)</code><br>
	 * <i>native declaration : iGammaJNAiGammaJNA.h:54</i><br>
	 * @deprecated use the safer methods {@link #iGammaJnaConnect(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} and {@link #iGammaJnaConnect(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	//@Deprecated 
	//public static native int iGammaJnaConnect(Pointer pszDBMSName, Pointer pszDBMSUserName, Pointer pszDBMSPass, Pointer pszDBUserName, Pointer pszDBPass, PointerByReference ppGamma, PointerByReference ppszError);
	/**
	 * Original signature : <code>int iGammaJnaConnect(const char*, const char*, const char*, const char*, const char*, void**, char**)</code><br>
	 * <i>native declaration : iGammaJNAiGammaJNA.h:54</i>
	 */
	public static native int iGammaJnaConnect(String pszDBMSName, String pszDBMSUserName, String pszDBMSPass, String pszDBUserName, String pszDBPass, PointerByReference ppGamma, PointerByReference ppszError);
	/**
	 * Original signature : <code>int iGammaJnaDisconnect(void*)</code><br>
	 * <i>native declaration : iGammaJNAiGammaJNA.h:56</i>
	 */
	public static native int iGammaJnaDisconnect(Pointer pGamma);
	/**
	 * Original signature : <code>int iGammaJnaGetLastError(void*, char**)</code><br>
	 * <i>native declaration : iGammaJNAiGammaJNA.h:57</i>
	 */
	public static native int iGammaJnaGetLastError(Pointer pGamma, PointerByReference ppszErrorMsg);
	/**
	 * Original signature : <code>int iGammaJnaFindObjects(void*, const char*, const IGAMMA_QUERYENTRY*, const int, ULONGLONG**, int*)</code><br>
	 * <i>native declaration : iGammaJNAiGammaJNA.h:59</i><br>
	 * @deprecated use the safer methods {@link #iGammaJnaFindObjects(com.sun.jna.Pointer, java.lang.String, integra.jna.IGAMMA_QUERYENTRY, int, com.sun.jna.ptr.PointerByReference, java.nio.IntBuffer)} and {@link #iGammaJnaFindObjects(com.sun.jna.Pointer, com.sun.jna.Pointer, integra.jna.IGAMMA_QUERYENTRY, int, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	//@Deprecated 
	//public static native int iGammaJnaFindObjects(Pointer pGamma, Pointer pszQueryName, IGAMMA_QUERYENTRY pQueryEntryList, int iEntryCount, PointerByReference ppResultList, IntByReference piResultCount);
	/**
	 * Original signature : <code>int iGammaJnaFindObjects(void*, const char*, const IGAMMA_QUERYENTRY*, const int, ULONGLONG**, int*)</code><br>
	 * <i>native declaration : iGammaJNAiGammaJNA.h:59</i>
	 */
	public static native int iGammaJnaFindObjects(Pointer pGamma, String pszQueryName, IGAMMA_QUERYENTRY pQueryEntryList, int iEntryCount, PointerByReference ppResultList, IntBuffer piResultCount);
	/**
	 * Original signature : <code>int iGammaJnaGetSystematicsData(void*, const ULONGLONG*, const int, IGAMMA_SYSTEMATIC**, int*)</code><br>
	 * <i>native declaration : iGammaJNAiGammaJNA.h:61</i><br>
	 * @deprecated use the safer methods {@link #iGammaJnaGetSystematicsData(com.sun.jna.Pointer, long[], int, com.sun.jna.ptr.PointerByReference, java.nio.IntBuffer)} and {@link #iGammaJnaGetSystematicsData(com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference, int, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	//@Deprecated 
	//public static native int iGammaJnaGetSystematicsData(Pointer pGamma, LongByReference pIdArray, int iIdArrayLength, PointerByReference ppSystematicList, IntByReference piLength);
	/**
	 * Original signature : <code>int iGammaJnaGetSystematicsData(void*, const ULONGLONG*, const int, IGAMMA_SYSTEMATIC**, int*)</code><br>
	 * <i>native declaration : iGammaJNAiGammaJNA.h:61</i>
	 */
	public static native int iGammaJnaGetSystematicsData(Pointer pGamma, long pIdArray[], int iIdArrayLength, PointerByReference ppSystematicList, IntBuffer piLength);
	/**
	 * Original signature : <code>int iGammaJnaGetBuildingsData(void*, const ULONGLONG*, const int, IGAMMA_BUILDING**, int*)</code><br>
	 * <i>native declaration : iGammaJNAiGammaJNA.h:63</i><br>
	 * @deprecated use the safer methods {@link #iGammaJnaGetBuildingsData(com.sun.jna.Pointer, long[], int, com.sun.jna.ptr.PointerByReference, java.nio.IntBuffer)} and {@link #iGammaJnaGetBuildingsData(com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference, int, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	//@Deprecated 
	//public static native int iGammaJnaGetBuildingsData(Pointer pGamma, LongByReference pIdArray, int iIdArrayLength, PointerByReference ppSystematicList, IntByReference piLength);
	/**
	 * Original signature : <code>int iGammaJnaGetBuildingsData(void*, const ULONGLONG*, const int, IGAMMA_BUILDING**, int*)</code><br>
	 * <i>native declaration : iGammaJNAiGammaJNA.h:63</i>
	 */
	public static native int iGammaJnaGetBuildingsData(Pointer pGamma, long pIdArray[], int iIdArrayLength, PointerByReference ppSystematicList, IntBuffer piLength);
}
