package integra.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : iGammaJNAiGammaJNA.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IGAMMA_QUERYRESULTS extends Structure {
	public int iSize;
	public long iObjectID;
	public IGAMMA_QUERYRESULTS() {
		super();
		setAlignType(Structure.ALIGN_NONE);
	}
	public IGAMMA_QUERYRESULTS(Pointer pointer) {
		super(pointer, Structure.ALIGN_NONE);
		read();
	}
   @Override
	protected List getFieldOrder() {
		return Arrays.asList("iSize", "iObjectID");
	}
	public IGAMMA_QUERYRESULTS(int iSize, long iObjectID) {
		super();
		this.iSize = iSize;
		this.iObjectID = iObjectID;
		setAlignType(Structure.ALIGN_NONE);
	}
	public static class ByReference extends IGAMMA_QUERYRESULTS implements Structure.ByReference {
		
	};
	public static class ByValue extends IGAMMA_QUERYRESULTS implements Structure.ByValue {
		
	};
}
